{{- range $value := .Values.ingress.tls}}
apiVersion: v1
kind: Secret
{{- if and $value.crt $value.key }} 
metadata:
  labels:
    app: {{ template "chatwoot.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  name: {{ $value.label }}
data:
  tls.crt: {{ $value.crt | b64enc | quote }}
  tls.key: {{ $value.key | b64enc | quote }}
{{- else }}
{{- $tlsCert := genSelfSignedCert (index $value.hosts 0) nil $value.hosts 365 }}
type: kubernetes.io/tls
metadata:
  name: {{ $value.label }}
  labels:
    app: {{ template "chatwoot.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
data:
  tls.crt: {{ $tlsCert.Cert | b64enc | quote }}
  tls.key: {{ $tlsCert.Key | b64enc | quote }}
{{- end }}
{{- end }}