{{- range $value := .Values.services}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  creationTimestamp: null
  labels:
    app: {{ template "chatwoot.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  {{- with $value.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: {{ int $value.internalPort }}
      targetPort: {{ int $value.targetPort }}
  type: {{ $value.type }}
  selector:
    app: {{ template "chatwoot.fullname" $ }}
    role: web
status:
  loadBalancer: {}
{{- end}}
